---
- name: Update and upgrade packages, reboot if needed
  hosts: all
  become: true

  tasks:
    # --- Ubuntu/Debian ---
    - name: Update package cache (apt)
      when: ansible_pkg_mgr == 'apt'
      ansible.builtin.apt:
        update_cache: true

    - name: Upgrade packages (apt)
      when: ansible_pkg_mgr == 'apt'
      ansible.builtin.apt:
        upgrade: dist
      notify: Check if reboot needed

    # --- RHEL/CentOS ---
    - name: Update and upgrade packages (yum)
      when: ansible_pkg_mgr == 'yum'
      ansible.builtin.yum:
        name: '*'
        state: latest
        exclude: kernel*
      notify: Check if reboot needed

  handlers:
    # === Debian/Ubuntu ===
    - name: Check reboot required on Debian/Ubuntu
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_required_file
      listen: Check if reboot needed
      when: ansible_pkg_mgr == 'apt'

    - name: Reboot if required (Debian/Ubuntu)
      ansible.builtin.reboot:
      when:
        - ansible_pkg_mgr == 'apt'
        - reboot_required_file.stat.exists
      listen: Check if reboot needed

    # === RHEL/CentOS ===
    - name: Check reboot required on RHEL/CentOS
      ansible.builtin.command: needs-restarting -r
      register: reboot_required_cmd
      failed_when: false
      changed_when: false
      listen: Check if reboot needed
      when: ansible_pkg_mgr == 'yum'

    - name: Reboot if required (RHEL/CentOS)
      ansible.builtin.reboot:
      when:
        - ansible_pkg_mgr == 'yum'
        - reboot_required_cmd.rc == 1
      listen: Check if reboot needed
